server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: warehouse-service
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fulfillx_warehouse}
    username: ${SPRING_DATASOURCE_USERNAME:fulfillx}
    password: ${SPRING_DATASOURCE_PASSWORD:fulfillx}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: warehouse-service
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      ack-mode: record
      observation-enabled: true

fulfillx:
  security:
    jwt:
      secret: ${JWT_SECRET:fulfillx-demo-jwt-secret-change-me-32bytes!!}
      issuer: fulfillx-auth
      audience: fulfillx-api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  structured:
    format:
      console: ecs
  level:
    com.fulfillx: INFO
