server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fulfillx_auth}
    username: ${SPRING_DATASOURCE_USERNAME:fulfillx}
    password: ${SPRING_DATASOURCE_PASSWORD:fulfillx}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

fulfillx:
  security:
    resource-server-enabled: false
    jwt:
      secret: ${JWT_SECRET:fulfillx-demo-jwt-secret-change-me-32bytes!!}
      issuer: fulfillx-auth
      audience: fulfillx-api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  structured:
    format:
      console: ecs
  level:
    com.fulfillx: INFO
