FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
ARG MODULE
ARG VERSION=1.0.0-SNAPSHOT
COPY services/${MODULE}/target/${MODULE}-${VERSION}.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-XX:+UseContainerSupport","-jar","/app.jar"]
